<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$objectManager = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$scopeConfig = $objectManager->getValue("opcmestremage/general/type_layout", $storeScope);
$custom_js = $objectManager->getValue("opcmestremage/general/custom_js", $storeScope);
$custom_css = $objectManager->getValue("opcmestremage/general/custom_css", $storeScope);
$shipping_address = $objectManager->getValue("opcmestremage/general/shipping_address", $storeScope);
$shipping_method = $objectManager->getValue("opcmestremage/general/shipping_method", $storeScope);
$payment_method = $objectManager->getValue("opcmestremage/general/payment_method", $storeScope);
$opc_sidebar = $objectManager->getValue("opcmestremage/general/opc_sidebar", $storeScope);
$authentication_button = $objectManager->getValue("opcmestremage/general/authentication_button", $storeScope);
$minimum_password_length = $objectManager->getValue("customer/password/minimum_password_length", $storeScope);

?>

<style>




    .custom-slide._show {
        left: 0px;
    }




    .g-recaptcha {
        display: block;
        clear: both;
    }





    .g-recaptcha>div {
        width: unset !important;

    }

    .form-login .actions-toolbar .primary {
        display: flex;
        width: 100%;
        justify-content: center;

    }


    .actions-toolbar .action.primary,
    .actions-toolbar .action.primary:hover {
        background: #f58a01;
        color: white;
        border: #f58a01;
        width: 100%;
        font-size: 17px;
        font-weight: 700;
    }

    #discount-form .payment-option-inner span {
        padding-left: 0px !important;
    }


    .actions-toolbar .action-remind {
        color: black !important;
        font-size: 14px;
    }

    .block-authentication .actions-toolbar>.primary .action {
        font-size: 15px !important;
    }

    .block-content .field {
        text-align: start !important;
    }

    #msp-recaptcha-checkout-login-wrapper {
        flex: 0 0 100%;
        max-width: 100%;
        position: relative;
        width: 100%;
        min-height: 1px;
        padding-right: 15px;
        padding-left: 15px;
        margin-top: 35px;
        left: 0px;
    }

    .rc-anchor-normal {
        width: unset !important;
    }

    .page-main .block {
        margin-bottom: 0px !important;
    }

    .payment-option-inner .control #discount-code {
        height: 31px;
    }

    #discount-form .action-apply,
    #discount-form .action-cancel {

        background-color: #5a905c;
        color: white !important;
        border: 0;
        font-weight: 600;
        font-size: 11px;
        padding-left: 10px;
        padding-right: 10px;

    }

    #discount-code-error {
        position: absolute;
    }


    .checkout-payment-method .payment-option-inner {

        margin-bottom: 0 !important;

    }

    .product-item-name {
        height: 0px;
        margin-bottom: 38px !important;

    }

    .modal-inner-wrap .modal-content {
        border: unset;
    }

    .action-login {
        background: #f58a01;
        color: white;

    }

    .action-login:hover,
    .action-login:active {
        background: #f58a01;
        color: white;
    }

    .modal-header {
        border-bottom: unset;
    }

    .custom-slide .modal-inner-wrap {
        background: white;
    }

    @media (max-width: 991px) {
        .authentication-wrapper {
            flex: 0 0 100%;
            max-width: 100%;
            padding-left: 10px;
            padding-right: 10px;

        }

        #discount-form .action-apply {
            display: block;
            width: 100%;
        }


        .col-payment-methods {
            margin-top: 30px;
        }




    }


    #checkout-shipping-method-load tbody .row {
        margin-left: 0;
        margin-right: 0;
    }




    @media (max-width: 425px) {
        #checkout-shipping-method-load tbody .row {
            display: grid;
            border-top: 1px solid #ccc;
        }

        #checkout-shipping-method-load tbody input[type="radio"] {
            margin: 0px 0px 0px 16px;
        }

        .table-checkout-shipping-method tbody td {
            border-top: unset;
        }


    }

    @media (max-width: 355px) {

        .g-recaptcha iframe {

            width: 100% !important;
        }

    }



    .payment-method-billing-address,
    #tooltip {
        display: none;
    }

    .field .control._with-tooltip input {
        margin-right: 10px;
        width: 100%;
    }


    .mark {
        background-color: unset !important;
    }

    .checkout-payment-method .payment-option-title .action-toggle {
        color: black;
        font-size: 16px;
    }


    .checkout-payment-method .payment-option-content {
        padding: 0 0 20px 2px;
    }

    #discount-form .payment-option-inner span {
        font-size: 12px;
        padding-left: 8px;
    }

    #checkout-step-shipping_method .no-quotes-block,
    .payment-group span {
        font-size: 17px;
    }

    .payment-method-content p {
    font-size: 16px;
}

    .checkout-payment-method .payment-method-content {
        padding-left: 0px;
    }

    .table-totals th,
    .table-totals span {
        font-size: 15px;
    }

    .osc select {
        font-size: 15px;
    }



    /*===MestreMage - One Step Checkout===*/
    div#checkout>.messages {
        display: none !important;
    }

    .osc .checkout-payment-method .payment-method-billing-address .billing-address-details {
        display: none;
    }

    .osc #co-payment-form ._active button.checkout {
        display: none;
    }

    .osc #co-payment-form .checkout-agreements {
        display: none;
    }

    .osc #opc-sidebar .action.primary {
        width: 100%;
    }

    .osc {
        /*padding: 20px 0;*/
        background: #ffffff;
        display: inline-block;
        vertical-align: top;
        width: 100%;
    }

    .osc>.col {
        width: 33.3333%;
        float: left;
        padding: 0 20px;
    }

    .rtl-layout .osc>.col {
        float: right;
    }

    .osc ul,
    .osc ol {
        padding: 0;
        list-style: none;
    }

    .osc input[type="text"],
    .osc input[type="password"],
    .osc input[type="url"],
    .osc input[type="tel"],
    .osc input[type="search"],
    .osc input[type="number"],
    .osc input[type="datetime"],
    .osc input[type="email"] {
        height: 45px;
        line-height: 32px;
        background-color: white;
        border: 1px solid #c7c5c5;
    }

    .osc select {
        height: 45px;
    }

    .rtl-layout .osc .step-title {
        padding: 8px 40px 8px 40px;
    }

    .checkout-billing-address {
        float: left;
        margin-top: 20px;
    }

    .osc .step-title:before {
        position: absolute;
        left: 18px;
        top: 5px;
        font-family: 'Pe-icon-7-stroke';
        speak: none;
        font-style: normal;
        font-weight: normal;
        font-variant: normal;
        text-transform: none;
        line-height: 1;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 26px;
    }

    .rtl-layout .osc .step-title:before {
        left: unset;
        right: 7px;
    }

    .osc .fieldset>.field>.label {
        font-weight: 500;
    }

    .osc .table-checkout-shipping-method {
        min-width: 100%;
    }

    .osc .form.methods-shipping {
        padding: 10px 0;
    }

    .osc .form.methods-shipping .table-checkout-shipping-method tbody td {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    .osc .shipping-address-item {
        border: 2px solid transparent;
        line-height: 30px;
        margin: 0 0 2rem;
        transition: 0.3s border-color;
        position: relative;
        vertical-align: top;
        word-wrap: break-word;
    }

    .osc .shipping-address-item.selected-item {
        border-color: #ff5501;
    }

    .osc .shipping-address-item.selected-item:after {
        background: #ff5501;
        color: #ffffff;
        font-family: 'icons-blank-theme';
        height: 27px;
        width: 29px;
        font-size: 27px;
        line-height: 21px;
        padding-top: 2px;
        position: absolute;
        right: 0;
        text-align: center;
        top: 0;
    }

    .osc .shipping-address-item.selected-item .action-select-shipping-item {
        visibility: hidden;
    }

    .osc .checkout-payment-method .step-title {
        margin-bottom: 20px;
    }

    .osc .checkout-payment-method .payment-method-title {
        border: 0 !important;
        padding: 0 0 5px;
    }

    .osc .checkout-payment-method .billing-address-details {
        border: 1px solid #e1e1e1;
    }

    .osc .checkout-payment-method .billing-address-details>span {
        display: block;
        padding-bottom: 10px;
    }

    .osc .checkout-payment-method .billing-address-details>br {
        display: none;
    }

    .osc .checkout-payment-method .payment-option-title {
        border-top: 0;
        padding: 10px;
        /* background: #f9f9f9; */
        margin-bottom: 5px;
    }

    .osc .checkout-payment-method .payment-option-title .action-toggle {
        display: block;
    }

    .osc .checkout-payment-method .payment-option-title .action-toggle:after {
        float: right;
        line-height: 20px;
    }

    .rtl-layout .osc .checkout-payment-method .payment-option-title .action-toggle:after {
        float: left;
    }

    .osc .checkout-payment-method .payment-method-content {
        padding-bottom: 0;
    }

    .osc .checkout-payment-method .payment-method-billing-address {
        margin-bottom: 0;
    }

    .osc .checkout-payment-method .payment-group {
        margin-bottom: 20px;
    }

    .osc .checkout-payment-method .payment-option-inner {
        margin: 10px 0;
    }

    .osc .checkout-payment-method .payment-option-inner .field>.label {
        margin: 0 0 8px;
        display: inline-block;
    }

    .osc .checkout-payment-method .billing-address-form {
        margin-bottom: 20px;
        margin-top: -10px;
    }

    .osc .payment-method {
        padding: 10px;
    }

    .osc #opc-sidebar .opc-block-summary {
        padding: 0;
        box-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        -o-box-shadow: none;
        -ms-box-shadow: none;
    }

    .osc #opc-sidebar .opc-block-summary .table-totals .grand strong {
        font-size: 16px;
    }

    .osc #opc-sidebar .opc-block-summary .minicart-items .product-item-name {
        font-size: 12px;
    }

    .osc #opc-sidebar .opc-block-summary .items-in-cart>.title,
    .osc #opc-sidebar .opc-block-summary .minicart-items .product-item,
    .osc #opc-sidebar .opc-block-summary .minicart-items .product-item:not(:first-child) {
        border-color: #e1e1e1;
    }

    .osc #opc-sidebar .actions-toolbar {
        width: 100%;
    }

    .osc #opc-sidebar .actions-toolbar .primary {
        width: 100%;
        margin: 0;
    }

    .osc #opc-sidebar .actions-toolbar .primary .action.primary {
        font-size: 20px;
        background: #f58a01 !important;
        border: 1px solid #f58a01 !important;
    }

    #checkout-step-shipping .action-show-popup {
        background: #f58a01 !important;
        font-weight: bold;
        font-size: 11px;
        color: white;
        border: 0px;
    }
    


    .action.action-select-shipping-item {
        background: #f58a01 !important;
        font-weight: bold;
        font-size: 11px;
        color: white;
        border: 0px;
        padding-top: 0px;
        padding-bottom: 0px;
    }


    .shipping-address-item {
        font-size: 14px;
    }


    .page-layout-1column .product-item-details {
        margin-top: 0!important; 
    }




    @media (max-width: 991px) {
        .osc>.col {
            width: 100%;
        }
    }

    @media (max-width: 767px) {

        .checkout-payment-method .payment-methods,
        .checkout-payment-method .payment-option {
            margin: 0;
        }
    }

    .opc-block-summary {
        background: #ffffff;
    }

    .groupe-col li {
        list-style: none;
    }

    fieldset.fieldset {
        display: contents;
    }

    input#mestremagentobl_cpf,
    input#mestremagentocc_cpf,
    input#mestremagentocc_fullname,
    .checkout-payment-method .ccard .number .input-text {
        width: 100% !important;
    }

    .fieldset>.field,
    .fieldset>.fields>.field {
        margin: 5 0 0 !important;
    }

    .osc div#checkout-step-shipping {
        padding-top: 15px
    }

    .osc span.note {
        font-size: 13px !important;
        color: #909090;
    }

    .osc div[name="shippingAddress.firstname"] {
        width: 50%;
        float: left;
    }

    .osc div[name="shippingAddress.lastname"] {
        width: 50%;
        float: left;
        padding-left: 10px;
    }

    .osc div[name="shippingAddress.telephone"] {
        clear: both;
        float: left;
        width: 47%;
    }

    .osc div[name="shippingAddress.fax"] {
        float: left;
        width: 47%;
        padding-left: 10px;
    }

    .osc div[name="shippingAddress.telephone"] .field-tooltip,
    .osc div[name="shippingAddress.fax"] .field-tooltip {
        display: none;
    }

    .osc div[name="shippingAddress.telephone"] .control._with-tooltip input,
    .osc div[name="shippingAddress.fax"] .control._with-tooltip input {
        width: 100% !important;
    }



    .osc div[name="shippingAddress.postcode"] {
        float: left;
        width: 100%
    }

    .osc div[name="shippingAddress.street.0"] {
        float: left;
        width: 70%
    }

    .osc div[name="shippingAddress.street.1"] {
        float: left;
        padding-left: 20px;
        width: 30%
    }

    .osc div[name="shippingAddress.street.2"] {
        float: left;
        width: 50%
    }

    .osc div[name="shippingAddress.street.3"] {
        float: left;
        padding-left: 20px;
        width: 50%
    }

    .osc div[name="shippingAddress.city"] {
        float: left;
        clear: both;
        width: 100%
    }

    .osc div[name="shippingAddress.region_id"] {
        float: unset;
        padding-left: 0;
        width: 100%
    }

    .osc div[name="shippingAddress.region_id"] select {
        height: 45px;
    }

    .osc div[name="shippingAddress.country_id"] select {
        height: 45px;
    }

    .osc .shipping-address-item.selected-item {
        padding: 10px;
    }

    /* DEIXANDO APENAS O LOGO E CENTRALIZANDO 
    .panel.wrapper,
    .minicart-wrapper,
    .block-search {
        display: none;
    }
    .logo{
        display: block;
        max-width: 100% !important;
        width: 100% !important;
    }
    .logo img{
        margin: 0px auto;
    }
	*/

    /* remove o layout de click no telefone */
    .checkout-index-index .shipping-address-item a {
        color: unset !important;
        text-decoration: unset !important;
        cursor: auto !important;
    }

    .checkout-index-index .shipping-address-item a:hover,
    .checkout-index-index .shipping-address-item a:visited {
        color: unset !important;
        text-decoration: unset !important;
        cursor: auto !important;
    }

    /* BOTAO DE LOGIN */
    .authentication-wrapper {
        clear: both;
        float: left;
        text-align: center;
        margin: 10px 0 0 0;
    }

    .authentication-wrapper button span {
        display: none;
    }

    .authentication-wrapper button:before {
        /* content: "<?= $authentication_button ?>"; */
        /* text-transform: uppercase !important; */
        content: "Quero me logar";

    }

    button.action.action-auth-toggle {
        background: #f58a01;
        color: white;
        border: #f58a01;
        width: 100%;
        font-size: 20px;
        font-weight: 700;
        height: 35px;
        text-decoration: none;

    }

    span.mm-msg-validation,
    span.mm-msg-validation-confirm {
        font-size: 11px;
        float: left;
        width: 100%;
        color: red;
    }


    @media (max-width: 992px) {
        .groupe-col {
            float: left;
            width: 90%;
            margin: 0 0 10px 0;
            padding: 3%;
        }

        .authentication-wrapper {
            width: 100%;
            padding-left: 3%;
            padding-right: 3%;
        }
    }

    @media (min-width: 993px) {
        .groupe-col {
            /* float: left;
            width: 30%;
            margin: 0 10px 0 0;
            padding: 1%;
          */
        }

        .authentication-wrapper {
            /* width: 30%; */
            /* padding: 1.1%; */
        }
    }

    .step-title.b-title.h3:before {
        margin: 3px;
        vertical-align: baseline;
        font-family: inherit;
        font-size: 20px;
        font-weight: bold;
    }

    .opc-block-summary>.title:before {
        margin: 0px 10px 0px -20px;
        vertical-align: baseline;
        font-family: inherit;
        font-size: 20px;
        font-weight: bold;
    }

    .checkout-shipping-address .step-title.b-title.h3:before {
        /*content: "<?= $shipping_address ?>";*/
        content: "1 - Endereço de entrega";

    }

    .checkout-shipping-method .step-title.b-title.h3:before {
        /*content: "<?= $shipping_method ?>";*/
        content: "2 - Métodos de envio";
    }

    .payment-group .step-title.b-title.h3:before {
        /*content: "<?= $payment_method ?>";*/
        content: "3 - Forma de pagamento";
    }

    .opc-block-summary>.title:before {
        /*content: "<?= $opc_sidebar ?>";*/
        content: "4 - Resumo do pedido";
    }

    .billing-address-details {
        display: none;
    }


    .fieldset>.field:not(.choice)>.label {
        padding: 6px 15px 0 0;
        text-align: left;
        width: 100%;
        box-sizing: border-box;
        float: left;
        font-size: 15px;
    }

    .fieldset>.field:not(.choice)>.control {
        width: 100%;
        float: left;
    }

    .osc .step-title,
    .osc #opc-sidebar .opc-block-summary>.title {
        font-size: 0;
        height: 35px;
    }

    /*layout 1*/
    <?php if ($scopeConfig == 1) : ?>.osc .step-title,
    .osc #opc-sidebar .opc-block-summary>.title {
        color: #ffffff;
        background: #5a905c;
        padding: 4px 8px 8px 40px;
        position: relative;
        font-weight: bold;
    }

    .groupe-col {
        /* border: 1px solid #ebebeb;
        border-radius: 20px; */
    }

    <?php endif; ?>
    /*layout 1*/

    /*layout 2*/
    <?php if ($scopeConfig == 2) : ?>.osc .step-title,
    .osc #opc-sidebar .opc-block-summary>.title {
        padding: 8px 8px 8px 40px;
        position: relative;
        font-weight: normal;
        color: #787878;
        border-bottom: 1px #c7c7c7 solid;
        text-transform: uppercase;
    }

    .groupe-col {
        border: 0px;
    }

    .opc-block-summary .table-totals {
        border-top: none;
    }

    <?php endif; ?>
    /*layout 2*/

    /*layout 3*/
    <?php if ($scopeConfig == 3) : ?>.osc .step-title,
    .osc #opc-sidebar .opc-block-summary>.title {
        color: white;
        background: #5a905c;
        padding: 8px 8px 8px 40px;
        position: relative;
        font-weight: bold;
    }

    .groupe-col {
        border: 1px solid #ebebeb;
        box-shadow: -5px 5px 12px 2px #e8e8e8;
    }

    <?php endif; ?>
    /*layout 3*/

    .groupe-col {
        max-width: 100%;
    }

    .opc-block-summary {
        border: none;
    }

    /*custom css*/
    <?= $custom_css ?>
</style>



<script>
    require([
        "jquery",
        "jquery/ui"
    ], function($) {
        $(document).ready(function() {

            var existCondition = setInterval(function() {
                var postcode = $('div#shipping-new-address-form [name*="shippingAddress.postcode"] [name*="postcode"]');
                var vat_id = $('div#shipping-new-address-form [name*="shippingAddress.vat_id"] [name*="vat_id"]');
                var telephone = $('div#shipping-new-address-form [name*="shippingAddress.telephone"] [name*="telephone"]');
                var fax = $('div#shipping-new-address-form [name*="shippingAddress.fax"] [name*="fax"]');
                var street_0 = $('div#shipping-new-address-form [name*="shippingAddress.street.0"]');
                var street_1 = $('div#shipping-new-address-form [name*="shippingAddress.street.1"]');
                var street_2 = $('div#shipping-new-address-form [name*="shippingAddress.street.2"]');
                var street_3 = $('div#shipping-new-address-form [name*="shippingAddress.street.3"]');
                var city = $('div#shipping-new-address-form [name*="shippingAddress.city"]');
                var region_id = $('div#shipping-new-address-form [name*="shippingAddress.region_id"]');
                var country_id = $('div#shipping-new-address-form [name*="shippingAddress.country_id"]');

                var input_street_0 = $('div#shipping-new-address-form [name*="shippingAddress.street.0"] [name*="street[0]"]');
                var input_street_1 = $('div#shipping-new-address-form [name*="shippingAddress.street.1"] [name*="street[1]"]');
                var input_street_2 = $('div#shipping-new-address-form [name*="shippingAddress.street.2"] [name*="street[2]"]');
                var input_street_3 = $('div#shipping-new-address-form [name*="shippingAddress.street.3"] [name*="street[3]"]');
                var input_city = $('div#shipping-new-address-form [name*="shippingAddress.city"] [name*="city"]');

                if (postcode.length) {
                    clearInterval(existCondition);
                    if (!postcode.val()) {
                        street_0.hide();
                        street_1.hide();
                        street_2.hide();
                        street_3.hide();
                        city.hide();
                        region_id.hide();
                        country_id.hide();
                    }
                    postcode.attr('inputmode', 'numeric');
                    vat_id.attr('inputmode', 'numeric');
                    telephone.attr('inputmode', 'numeric');
                    fax.attr('inputmode', 'numeric');

                    postcode.attr('autocomplete', 'off');
                    input_street_0.attr('autocomplete', 'off');
                    input_street_1.attr('autocomplete', 'off');
                    input_street_2.attr('autocomplete', 'off');
                    input_street_3.attr('autocomplete', 'off');
                    input_city.attr('autocomplete', 'off');

                    postcode.on('keyup input', function() {
                        if ($(this).val().length >= 8) {
                            street_0.show('slow');
                            street_1.show('slow');
                            street_2.show('slow');
                            street_3.show('slow');
                            city.show('slow');
                            region_id.show('slow');
                            country_id.show('slow');
                        }
                    });
                }
                $('span#block-discount-heading').click(function() {
                    $('button.action.action-apply').prop('type', '');
                });

            }, 100);

        });

        <?= $custom_js ?>
    });
</script>


<script>
    require([
        "jquery",
        "jquery/ui"
    ], function($) {

        var minimum_password_length = "<?= $minimum_password_length ?>";

        var existCondition = setInterval(function() {
            if ($('[name="code-confirm_password"]').length) {
                clearInterval(existCondition);
                $('<span class="mm-msg-validation-confirm"></span>').insertAfter('[name="code-confirm_password"]');
                $('<span class="mm-msg-validation"></span>').insertAfter('[name="code-password"]');

                $('[name="code-password"]').change(function() {
                    var password = $('[name="code-password"] [name="code-password"]');
                    if (parseInt(password.val().length) < parseInt(minimum_password_length)) {
                        password.css("border", "red solid 1px");
                        $('.mm-msg-validation').text('A senha precisa de pelo menos ' + minimum_password_length + ' caracteres');
                    } else {
                        password.css("border", "initial");
                        $('.mm-msg-validation').text('');
                    }
                })

                $('[name="code-confirm_password"]').change(function() {
                    var password = $('[name="code-password"] [name="code-password"]');
                    var confirm_password = $('[name="code-confirm_password"] [name="code-confirm_password"]');
                    if (confirm_password.val() != password.val()) {
                        confirm_password.css("border", "red solid 1px");
                        $('.mm-msg-validation-confirm').text('As senhas não conferem.');
                    } else {
                        confirm_password.css("border", "initial");
                        $('.mm-msg-validation-confirm').text('');
                    }
                })

                var mage_cache_storage = JSON.parse(window.localStorage.getItem('mage-cache-storage').replace("checkout-data", "checkout_data"));
                if (mage_cache_storage.checkout_data.checkedEmailValue && typeof mage_cache_storage.checkout_data.checkedEmailValue !== 'undefined') {
                    $('#customer-email').val(mage_cache_storage.checkout_data.checkedEmailValue);
                    showInputLogin();
                } else {
                    $('#customer-email').val('');
                    $('.hidden-fields').hide();
                    $('[name="code-password"]').hide();
                    $('[name="code-confirm_password"]').hide();
                }
            }
        }, 100);

        (function() {
            const send = XMLHttpRequest.prototype.send;
            XMLHttpRequest.prototype.send = function() {
                this.addEventListener('load', function() {
                    if (this.responseURL.indexOf("shipping-information") != -1) {
                        updateInstallmentsPagSeguro();
                    }
                    if (this.responseURL.indexOf("isEmailAvailable") != -1) {
                        if (this.responseText == 'true') {
                            showInputRegister();
                        } else {
                            showInputLogin();
                        }
                    }
                });
                return send.apply(this, arguments)
            }
        })();


        function showInputRegister() {
            $('.hidden-fields').hide();
            //$('[name="code-password"]').show();
            //$('[name="code-confirm_password"]').show();
            $('#customer-email-fieldset .control._with-tooltip .note').removeClass('d-none');

        }

        function showInputLogin() {
            $('.hidden-fields').show();
            //$('[name="code-password"]').hide();
            //$('[name="code-confirm_password"]').hide();
            $('#customer-email-fieldset .control._with-tooltip .note').addClass('d-none');
        }

        function updateInstallmentsPagSeguro() {
            if (typeof RMPagSeguro != 'undefined') {
                var url = BASE_URL + 'pseguro/ajax/getGrandTotal';
                $.ajax({
                    url: url,
                    success: function(response) {
                        RMPagSeguro.prototype.setStoreUrl(BASE_URL);
                        RMPagSeguro.prototype.setGrandTotal(response.total);
                        RMPagSeguro.prototype.updateCreditCardToken();
                    },
                    error: function(response) {
                        return false;
                    }
                });
            }
        }
    });
</script>